### PR TITLE
Proposal for full-width video

### PR DESCRIPTION
**Pull request by chkworks**
Hey there! As written a few weeks ago in the chat, I would like to start several attempts to improve the overall user experience, consistency and maybe then some time in the future a proper screen design. In the next weeks I want to push little changes, especially for font sizes and weights. 

Here is the first proposal, re-introducing the full-width video that was on the page before. The headlines, text and links were completely duplicated between carousel and first card. Also it is more attractive, if there is something moving from the start.

Things to consider:
- Should we host the video as HTML5 video or on Vimeo, to get rid of all the UI elements and the YouTube logo? I could offer to host on Vimeo, we have an account that allows custom branding.
- Is there a need for a new video? Maybe make a call for content in the community?
- Can we put the history section of Stride on a separate landing page?
- Can we unify the cards "Accelerated development" and "Write your Stride scripts in C# 10" into one? They pretty much claim the same things.

If you like the ideas, please tell me so I can little by little move on with this :)

### CODE REVIEW

**Comment by VaclavElias** [comment]
Hi @chkworks,

We would be happy to implement any improvements that could make the Stride website more attractive and user-friendly. As a full-time C# web developer, not a designer/artist, I revamped the website to my capacity, utilizing the latest Bootstrap 5 with a goal to minimize the use of gears and plugins for long-term maintainability. The update involved only minor content changes, easing the transition to this revamped website with minimal involvement from the core maintainers since only the design was altered while the content remained mainly unchanged.

Bootstrap 5's recent dark theme inclusion means we only need minor adjustments for this feature. I don't use a dark theme personally, so I implemented it as an experiment for others to refine.

Concerning the video and other your points, here are my thoughts:

- While testing Azure Static Site hosting, which has limited space, I proposed housing large media files externally, be it on YouTube or Vimeo. I'd begin with YouTube, awaiting xen2's approval for also using Vimeo for some website content.
- New video or image contributions are appreciated, although sourcing them may not be straightforward. You could engage our Discord community or initiate a new discussion to invite content creators for more video or image contributions.
- Regarding relocating the history section of Stride to a separate landing page, I'd defer to @tebjan and @Eideren for insights as I'm unsure of the necessity to feature it on the home page. Maybe it made sense in the past.
- For "Accelerated development" and "Write your Stride scripts in C# 10," SEO plays a significant role. The former likely appeals to game developers, while I introduced the latter as an h2 tag to enhance SEO by referencing C# 10, .NET6, and related benefits, targeting C# developers and coders. The "Accelerated development" is original content, which I didn't want to change too much so I added the "Write your Stride scripts in C# 10" section to appeal more to C# devs and help with SEO. Probably long term, there should be a dedicated page for this section as it would hugely help with the intention.

I'm available to assist with certain aspects, though some decisions will require broader consultation with the core maintainers🙂. I hope this is ok 🙂.

**Comment by chkworks** [comment]
Hey! Thank you for the detailed answer! And also for the huge effort with the website!

if you are okay with this, I suggest to continue in the upcoming weeks on these two things - I think they will improve the design already, and are relatively quick to implement:

- Reintroduce the video section
- Polish font sizes and weights

It would be great to find a hosting solution for the video, that allows to remove all branding from the hoster. Vimeo can do that with a paid account. I can offer to do that from our studio account (https://vimeo.com/threeeeight).

About sourcing new video material - I can imagine to take responsibilty there. But I suggest, we first get the video section back in place, and postpone this to earlier next year. what do you think?

**Comment by VaclavElias** [comment]
You are welcome.

Sure, let's go ahead with those 2 points. 

If we host it again ourselves, would that work? Just considering all options.

I believe sourcing a new video might be a bit of work, including what should be the content and how to deliver the right message. But I will leave that with you, once you go ahead, I believe you can gather more info from the community. This was recently released if that is helpful https://github.com/stride3d/RescueDrone

Definitely, we can get the existing video back. 

Thanks again.

**Comment by chkworks** [comment]
"If we host it again ourselves, would that work? Just considering all options."

Yes, sure, but afaik on Vimeo there is no possibility to remove all user interface elements from the embedded player on a free plan. This requires a plus plan. Do you have one? Or do you refer to hosting it as a HTML5 video?

**Comment by VaclavElias** [comment]
Yes, I referred to hosting it as a HTML5 video again on our web server.

**Comment by chkworks** [comment]
Okay, then I guess I will wait with further work on this until I know where the video should be hosted.

**Comment by VaclavElias** [comment]
I don't want to stop you, we are already hosting videos ourselves, for example https://github.com/stride3d/stride-website/tree/master/images/features/graphics so that is our fallback. It was just a suggestion hosting it somewhere else so we don't have to drag 180 MB every time we deploy a  new version. We can leave the hosting improvements for later as in the meantime we can host it locally like the current videos 🙂

**Comment by VaclavElias** [comment]
Some resources if needed https://www.figma.com/file/LwUrbnxR1hVkO53R3yqpQT/STRIDE3D?type=design&node-id=126-192&mode=design

**Comment by chkworks** [comment]
Hey! So here is some more work on this draft. If this is okay for you, I will finish with the following in the next days:

- Check all responsive breakpoints for the front page
- Transfer font weights and sizes to all other landing pages

Let me know!

**Comment by VaclavElias** [comment]
It looks good. Thank you very much. The video is actually quite impressive to see it on a big screen. Please go ahead. Just some small things I noticed, which you might be aware of.

The `intro-video` class is currently causing a horizontal bar on Chrome, any screen size width. 

image

The image rations will need to be adjusted. By the way, very good choice of the image for the Bet on the future section.

image

I see you are also doing some content improvements. Please continue in that direction as well.

**Comment by chkworks** [comment]
Speaking of the content improvements - it would be great to also include in this PR to get rid of the history on the front page, if possible. This should belong into a separate landing page, which I can take care of. (@Eideren @tebjan)

Also I would propose to extend the sponsors view, so not only two sponsors are listed there. OpenCollective promises everyone who is at least a Silver Stride to be listed on the front page, so that should be done here, right? Godot is displaying sponsors quite nicely.

**Comment by chkworks** [comment]
So... here are a bunch of other proposals, and quite a few content and styling suggestions. 
I think we should have four main sections on the front page:

- Everything related to features and the editor
- Everything related to development, coding and the ecosystem
- NEW: A separate section for documentation, manuals, tutorials
- The community section

On the long run, I think these could either be split up into separate cards, describing single core features (see Godot front page again), or they should like to **separate** pages with their buttons. Right now, the buttobs of the sections "Bet on the future" and "Accelerated Development" link to the same page. IMO, these two should be two completely different pages, which will increase SEO more than repeating headlines.

I also want to propose to remove the description and tags from the sponsors... I find this information too much. Also I have removed the history section, for this I propose to have a dedicated landing page in the footer named "History".

**Comment by VaclavElias** [comment]
Thank you again @chkworks. Again, I like the most recent update which I tested locally.

I like the idea of 4 sections or more if needed and put things logically together.

I had also an idea, to show last 2-3 blog posts cards at the bottom, which could help SEO linking..

I agree, that eventually, some of them could be separated cards (more content), linking ideally to the separate pages (more content). We need technical content writers ( I am not a game dev) who could assist with the relevant content.

Saying, that we mentioned a few time separated pages, that means, that top navigation should have some kind sub menus? As I mentioned, I didn't change too much content when I was doing an upgrade to 11ty, so it was easy to keep the top navigation as it is, but with more content pages, we would need to work on that part as well.. once there is more content. Also, some features from the features page should link to separate pages, which would help with SEO.

I am ok with the Sponsors card update on the home page (note those includes are also reused on the sponsor.md page) but I would need to check with others..

**Comment by VaclavElias** [comment]
@Aggror, could you give us any comments?

**Comment by Aggror** [comment]
I am all for webdesign improvement, but those are not my cup of tea. I can only often in hindsight nod and say: oh yeah that looks better. I would have to try and build the site locally again, to see the changes.

A custom widget for the Open Collective sponsors might be necessary like you mentioned @VaclavElias. They do not look pretty in the dark theme anyway, and their non responsiveness don't make things any prettier.

Having VVVV with a large image and description is pretty nice imo. I think it adds something that there is a brief explanantion on why they are top contributors. The tags look slighly our of place with their different colors. Maybe remove just those?

As for the Vimeo account: if we are also going to host on Vimeo, it would have to be with an official account. For 15 dollars a month for 60 videos. I am not sure if that is really worth it though. Sure there is some money available, but is Youtube really that bad? Wouldn't that money be better spend on other things?

**Comment by chkworks** [comment]
Thank you for your answers! I would really appreciate if you built the website locally and compared it to the current state. Most of all I was suggesting content changes, besides the big video on the front page. There are so far only minor design changes.

Right now the Video is hosted on YouTube, and although I was in doubt, I think it works great with the UI elements of the video player. So I think, we actually don't really need the Vimeo solution, which I anyway offered to take on my account (see my second comment)

The idea of having the lastest three posts on the front page is very good, I think. At the moment, I would mainly need an opinion if you are okay with the suggestion to move the Stride history part to a separate landing page.

**Comment by xen2** [comment]
I agree that history used to be useful right after the switch from commercial to OSS as users were stuck in limbo for a while, but not anymore.
I'm fine to move or remove it.

**Comment by VaclavElias** [comment]
I will create a separate branch, where we can merge this. Then I will be able to deploy it to staging. Are you ok to with that?

**Comment by chkworks** [comment]
Sure! Whatever works best... also exciting for me to see what steps are necessary. There are also conflicting files as shown in this PR, but I don't know how to solve this, should I do something about it?

**Comment by VaclavElias** [comment]
The conflicts are there because we have recently updated also `index.md`. But we should select your updates.. Maybe it will get resolved by these steps.

I have created a new branch `demo-updated-design`, could you clone this branch, apply your changes on this branch and create a PR to this branch `demo-updated-design`? This way, I should be able to deploy it to our staging environment so we can further elaborate.

Another option (more fiddling) is, that you can use GitHub Pages, and deploy with GitHub Action the website to your repo GitHub Pages, this way you can see your updates right away and you can ping us to see your most recent updates. If needed, here is GitHub Action I used in the past https://github.com/VaclavElias/stride-website-next/blob/main/.github/workflows/stride-web-staging-github.yml

**Comment by chkworks** [comment]
Okay, I have checked out the mentioned branch and added my changes there. But I don't know what to do here... could you help me out?

Bildschirmfoto 2023-10-12 um 10 56 02

**Pull request closed without merging**
