### PR TITLE
Convert top ~20 largest images (by file size) to WebP

### PR DESCRIPTION
**Pull request by parhamgholami**
Following up on https://github.com/stride3d/stride-website/issues/126, I've converted 22 of the largest images by file size to WebP and updated references to the images on the site accordingly. This should help reduce the footprint of parts of the site without sacrificing the overall quality of the images.

With this in mind, I was unable to identify where the following files are used on the site, so they were skipped:
- \images\og\ogp.jpg
- \images\showcase\sengokurun.jpg
- \images\blog\release-1.0-alpha\XenkoStudio_1_0_0_alpha07.jpg
- \images\blog\release-2.0\light_probes.jpg
- \images\external\script-editor.png
- \images\showcase\JumpyJet2D.jpg
- \images\features\graphics\vr.jpg

I can go back and convert these too, if we know where the references need to be updated.

### CODE REVIEW

**Comment by VaclavElias** [comment]
One last thing. There is one **new** file which shouldn't be there and we don't need it. Could you remove `package-locks.json`. Note that `s` at the end. Maybe some backup file on your side 🤣.

**Comment by parhamgholami** [comment]
Whoops! Was doing some quick and dirty debugging and that slipped through heh. Removed the file.

**Review by VaclavElias — APPROVED** [review]
All seems ok. Thanks.

**Comment by VaclavElias** [comment]
Thank you @parhamgholami

**Pull request merged**
